--- #YAML:1.0
name: DateTime-Fiscal-Year
version: 0.02
license: perl
distribution_type: module
requires:
  DateTime: 0.07
  perl: 5.005_03
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Fiscal::Year:
    file: lib/DateTime/Fiscal/Year.pm
    version: 0.02
generated_by: Module::Build version 0.20
